server:
  port:8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CustomerDB
    password: sapasswork
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
    - Customer
    redis:
      key-prefix: test
      time-to-live: 60000
      cache-null-values: true
  application:
    name: CUSTOMER-SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
debug: true

